name: second workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Different Repository
        uses: actions/checkout@v2
        with:
          repository: shreya0522/spring3hibernate
          ref: main

      - name: list 
        run: ls -la
